name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Login, build, and push to GitHub Docker Registry
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
         DOCKER_TAG=$(echo "${GITHUB_SHA}" | cut -c1-12)
         docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}:${DOCKER_TAG} .
         docker tag docker.pkg.github.com/${GITHUB_REPOSITORY}:${DOCKER_TAG} docker.pkg.github.com/${GITHUB_REPOSITORY}:latest
         docker push docker.pkg.github.com/${GITHUB_REPOSITORY}
